{% set name = "sidetable" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 363d90e4ec0e83699ad34e4d688806e1156e9ebbe6a1d229ab5d44c8229c8a9d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pandas >=1.0
    - python >={{ python_min }}

test:
  imports:
    - sidetable
  requires:
    - pytest
    - seaborn
    - python {{ python_min }}

about:
  home: https://github.com/chris1610/sidetable
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: sidetable builds simple but useful summary tables of your pandas data

extra:
  recipe-maintainers:
    - chris1610
